// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwr-FfBZKnzY-SlWducmqA9Iu2Rm07cTo',
    appId: '1:185980528485:web:0a456dc2b2e7dcce52e38c',
    messagingSenderId: '185980528485',
    projectId: 'third-application-notes',
    authDomain: 'third-application-notes.firebaseapp.com',
    storageBucket: 'third-application-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-winVtnLzfYc2NXE6J-D2nNGpLo_Wosk',
    appId: '1:185980528485:android:9658ff9c9a109aab52e38c',
    messagingSenderId: '185980528485',
    projectId: 'third-application-notes',
    storageBucket: 'third-application-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIkrKp_rD-5UUWGrUdDu54ACbldUBh2As',
    appId: '1:185980528485:ios:a537cc0f4aa3c55e52e38c',
    messagingSenderId: '185980528485',
    projectId: 'third-application-notes',
    storageBucket: 'third-application-notes.appspot.com',
    iosClientId: '185980528485-fcavhp642duukdqn71e82mhi3ls0so4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.secandnoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIkrKp_rD-5UUWGrUdDu54ACbldUBh2As',
    appId: '1:185980528485:ios:a537cc0f4aa3c55e52e38c',
    messagingSenderId: '185980528485',
    projectId: 'third-application-notes',
    storageBucket: 'third-application-notes.appspot.com',
    iosClientId: '185980528485-fcavhp642duukdqn71e82mhi3ls0so4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.secandnoteapp',
  );
}
